### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by Jasper-Ben** [mill1000/warthog#1]
Just as a heads up, this project is missing an appropriate license, which will(/should) prevent anyone (who takes license compliance seriously) from using this.

As it includes mongoose which is dual licensed (GPLv2 or commercial license) this project will have to fall under the terms of the GPLv2, if no mongoose commercial license has been purchased, which makes licensing this library tricky when using this in a commercial product.

IANAL but I believe an appropriate license could be:
Dual licensed GPLv2 | (Apache-2.0/MIT/... other permissive OS license) with the latter only applicable if a commercial mongoose license has been purchased.

**Comment by mill1000** [comment]
Hey thanks for the heads up. I'll need to review the information but your recommendation does make sense to me.

**Comment by mill1000** [comment]
I'm no expert, but based on this [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL) I'm thinking I could simply license this project with a GPLv2 compatible license (perhaps [MIT/Expat](https://www.gnu.org/licenses/license-list.html#Expat)).

Any work utilizing Mongoose via GPLv2 would be required to comply with GPLv2, which the above license would allow. Any commercially licensed work would still be able to utilize this project if the GPL-compatible license allows it.

Thoughts? Am I missing something obvious?

**Comment by Jasper-Ben** [comment]
👋 

that will not work. The import direction is important. When we talk about MIT beeing "GPL compatible" we mean that a GPL licensed software may include a MIT licensed software. That does NOT apply the other way around. Rule of thumb: software may include equally or lesser copyleft protected libraries.

So for example if you would license this under the MIT license and mongoose (GPL/commercial licensed) would decide to add a include statement for adding your library, that would be fine. But you including mongoose (as you do in https://github.com/mill1000/warthog/blob/be0757250d9b544b9fb6553100e46ceba8ddc066/warthog.h#L8) would not.

The FAQ you posted states this clearly:

"""
If a library is released under the GPL (not the LGPL), does that mean that any software which uses it has to be under the GPL or a GPL-compatible license? ([#IfLibraryIsGPL](https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL))

    Yes [...]
"""

Thats why you need the GPL included in a dual license, so that your software may be GPL compatible if no mongoose commercial license has been purchased.

I will create a PR in a bit 🙂

**Comment by Jasper-Ben** [comment]
Well actually the FAQ does not state it clearly and I understand your confusion now. What probably happpened is that you read their "a GPL-compatible license" (which is honestly really badly done on their part) and then you probably googled "is MIT GPL compatible?" and the answer was "yes", however this would have been referencing the "GPL including MIT" case.

What the FAQ means by "GPL-compatible" is a license providing equal or stricter copyleft protection, so basically a license which requires you to release source code (which MIT does not).

**Comment by mill1000** [comment]
Thanks for the PR. The whole situation is still muddy to me, but I'll trust your judgement.

**Comment by Jasper-Ben** [comment]
> Thanks for the PR. The whole situation is still muddy to me, but I'll trust your judgement.

No worries, license compliance is a complicated topic and thanks for the (hopefully deserved) trust. :sweat_smile:
